name: Build and publish docker image

on:
  workflow_call:
    inputs:
      release-version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Read env file
      #   id: read_env
      #   uses: cardinalby/export-env-action@v2
      #   with:
      #     envFile: '.env'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Generate docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          context: git
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ inputs.release-version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ inputs.release-version }}
            type=semver,pattern={{major}},value=${{ inputs.release-version }}
          # labels:
          #   kea.version=${{ env.KEA_VERSION }}
          #   alpine.version=${{ env.ALPINE_VERSION }}
          flavor: |
            latest=true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64,linux/amd64
          file: "Dockerfile"
          # build-args: |
          #   KEA_VERSION=${{ env.KEA_VERSION }}
          #   ALPINE_VERSION=${{ env.ALPINE_VERSION }}
